### ISSUE TITLE
Why the use of a lambda function?

### ISSUE THREAD

**Issue by marier-nico** [QuiNovas/terraform-aws-s3-bucket-replicator#9]
Hello,

I was browsing Terraform modules, looking to see if anyone made an easy bucket replication module and stumbled across this one. I looked through the code a bit and was very surprised to find the use of a Lambda function to replicate objects. Is there any reason why someone would want to do this instead of using native S3 Bucket replication as documented [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#using-replication-configuration)?

I'm genuinely curious to know if there may be flaws in the official method or if the Lambda approach may be better for some cases. If not, perhaps it would be more efficient to use a more standard method! This certainly seems more complex than it needs to be at first glance :thinking:

**Comment by joseph-wortmann** [comment]
No problem. Standard S3 replication is just fine if you only want to replicate to one other bucket and you are fine with a primary/secondary replication strategy.

The replicator created by this module replicates to multiple buckets, which was a requirement that I had when I wrote it. Currently it is being used to replicate Lambda packages to multiple regions across the world (build and post to us-east-1, replicate from there).
